--!!!PRECONDITION!!!! create QueryWrapper Scripts (used for logging)
--load it from https://raw.githubusercontent.com/EXASOL/etl-utils/master/query_wrapper.sql
CREATE OR REPLACE TABLE PRESCRIPTIONS_UK_STAGE.PRESCRIPTIONS
	(
		SHA CHAR(3),
		PCT CHAR(3),
		PRACTICE CHAR(6),
		BNF_CODE CHAR(15),
		BNF_NAME VARCHAR(50),
		ITEMS DECIMAL(9),
		NIC DECIMAL(10, 2),
		ACT_COST DECIMAL(10, 2),
		QUANTITY DECIMAL(9),
		PERIOD DECIMAL(6)
	) ;
CREATE OR REPLACE TABLE PRESCRIPTIONS_UK_STAGE.CHEMICAL_SUBSTANCES
	(
		CHEM_SUB CHAR(9),
		CHEMICAL_NAME VARCHAR(1000),
		unknown_field VARCHAR(1000)
	) ;
CREATE OR REPLACE TABLE PRESCRIPTIONS_UK.CHEMICAL_SUBSTANCES
	(
		SK_CHEM_SUB DECIMAL(9) IDENTITY NOT NULL,
		CHEM_SUB CHAR(9) NOT NULL,
		CHEMICAL_NAME VARCHAR(40) NOT NULL,
		PRIMARY KEY(SK_CHEM_SUB)
	) ;
--insert dummy value cause some BNF_CODE values have no data in Lookup table
INSERT
INTO    PRESCRIPTIONS_UK.CHEMICAL_SUBSTANCES
	(
		CHEM_SUB,
		CHEMICAL_NAME
	)
	VALUES
	(
		'*NO_DATA*',
		'*** DATA MISSING IN LOOKUP TBL ***'
	) ;
CREATE OR REPLACE TABLE PRESCRIPTIONS_UK_STAGE.PRACTICE_ADDRESS
	(
		PERIOD DECIMAL(6),
		PRACTICE CHAR(6),
		PRACTICE_NAME VARCHAR(50),
		ADDRESS_PART1 VARCHAR(50),
		ADDRESS_PART2 VARCHAR(50),
		ADDRESS_PART3 VARCHAR(50),
		ADDRESS_PART4 VARCHAR(50),
		POSTCODE_FULL VARCHAR(50)
	) ;
CREATE OR REPLACE TABLE PRESCRIPTIONS_UK.PRACTICE_ADDRESS
	(
		SK_PRACTICE_ADDRESS DECIMAL(9) IDENTITY NOT NULL,
		PERIOD DECIMAL(6) NOT NULL,
		PRACTICE CHAR(6) NOT NULL,
		PRACTICE_NAME VARCHAR(50),
		ADDRESS_PART1 VARCHAR(50),
		ADDRESS_PART2 VARCHAR(50),
		ADDRESS_PART3 VARCHAR(50),
		ADDRESS_PART4 VARCHAR(50),
		POSTCODE_FULL VARCHAR(50) NOT NULL, --detailed information (as it is in the data
		-- with outwards and inwards code
		POSTCODE VARCHAR(5) NOT NULL -- only outwards code
		,
		PRIMARY KEY(SK_PRACTICE_ADDRESS)
	) ;
CREATE OR REPLACE TABLE PRESCRIPTIONS_UK.PRESCRIPTIONS
	(
		SHA CHAR(3) NOT NULL,
		PCT CHAR(3) NOT NULL,
		PRACTICE CHAR(6) NOT NULL,
		BNF_CODE CHAR(15) NOT NULL,
		BNF_NAME VARCHAR(50),
		ITEMS DECIMAL(9),
		NIC DECIMAL(10, 2),
		ACT_COST DECIMAL(10, 2),
		QUANTITY DECIMAL(9),
		PERIOD DECIMAL(6),
		PERIOD_FIRST_DAY_AS_DATE DATE, -- for convenience when using frontends
		SK_CHEM_SUB DECIMAL(9) NOT NULL, -- added to make the lookup easier
		SK_PRACTICE_ADDRESS DECIMAL(9) NOT NULL, -- added to make the lookup easier
		FOREIGN KEY(SK_CHEM_SUB) REFERENCES PRESCRIPTIONS_UK.CHEMICAL_SUBSTANCES
		(SK_CHEM_SUB),
		FOREIGN KEY(SK_PRACTICE_ADDRESS) REFERENCES PRESCRIPTIONS_UK.PRACTICE_ADDRESS
		(SK_PRACTICE_ADDRESS)
	) ;
CREATE OR REPLACE TABLE PRESCRIPTIONS_UK_STAGE.raw_data_urls
	(
		description VARCHAR(100),
		period DATE,
		url VARCHAR(100),
		loaded_timestamp TIMESTAMP
	) ;
--setup logging
CREATE OR REPLACE TABLE PRESCRIPTIONS_UK_STAGE.job_log
	(
		run_id INT identity,
		script_name VARCHAR(100),
		status VARCHAR(100),
		start_time TIMESTAMP DEFAULT systimestamp,
		end_time TIMESTAMP
	) ;
CREATE OR REPLACE TABLE PRESCRIPTIONS_UK_STAGE.job_details
	(
		detail_id INT identity,
		run_id INT,
		log_time TIMESTAMP,
		log_level VARCHAR(10),
		log_message VARCHAR(2000),
		rowcount INT
	) ;
--set distribution keys for local joins (reduced network communication)
ALTER TABLE PRESCRIPTIONS_UK.PRACTICE_ADDRESS DISTRIBUTE BY SK_PRACTICE_ADDRESS;
ALTER TABLE PRESCRIPTIONS_UK.PRESCRIPTIONS DISTRIBUTE BY SK_PRACTICE_ADDRESS;